CREATE TABLE LEAVE_TYPES
(
  LT_ID            NUMBER,
  SHORT_CODE       VARCHAR2(5 BYTE),
  LEAVE_TYPE_NAME  VARCHAR2(50 BYTE)            NOT NULL,
  DESCRIPTION      VARCHAR2(100 BYTE),
  ANNUAL_QUOTA     NUMBER,
  IS_PAID          CHAR(1 BYTE),
  ACTIVE_FLAG      CHAR(1 BYTE)                 DEFAULT 'Y',
  ENT_BY           VARCHAR2(50 BYTE),
  ENT_DATE         DATE                         DEFAULT SYSDATE,
  UPD_BY           VARCHAR2(50 BYTE),
  UPD_DATE         DATE,
  COM_ID           NUMBER
);


CREATE UNIQUE INDEX LEAVE_TYPES_PK ON LEAVE_TYPES
(LT_ID);

ALTER TABLE LEAVE_TYPES ADD (
  CHECK (is_paid IN ('Y', 'N'))
  ENABLE VALIDATE
,  CHECK (active_flag IN ('Y', 'N'))
  ENABLE VALIDATE
,  CONSTRAINT LEAVE_TYPES_PK
  PRIMARY KEY
  (LT_ID)
  USING INDEX LEAVE_TYPES_PK
  ENABLE VALIDATE);
