CREATE TABLE HR_EMPLOYEE_PROMOTION
(
  PROMOTION_ID       NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 121 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  PROMOTION_NO       VARCHAR2(30 BYTE),
  EMP_ID             NUMBER                     NOT NULL,
  ACTION_ID          NUMBER,
  PROMOTION_TYPE     VARCHAR2(20 BYTE)          DEFAULT 'REGULAR'             NOT NULL,
  ACCELERATED_COUNT  NUMBER(3),
  PROMOTION_DATE     DATE                       DEFAULT SYSDATE               NOT NULL,
  EFFECTIVE_DATE     DATE                       NOT NULL,
  OLD_EMP_TYPE_ID    NUMBER,
  NEW_EMP_TYPE_ID    NUMBER,
  OLD_JOB_ID         NUMBER,
  NEW_JOB_ID         NUMBER,
  OLD_DESIG_ID       NUMBER,
  NEW_DESIG_ID       NUMBER                     NOT NULL,
  OLD_DEPT_ID        NUMBER,
  NEW_DEPT_ID        NUMBER,
  OLD_BASIC          NUMBER(14,2),
  NEW_BASIC          NUMBER(14,2)               NOT NULL,
  OLD_GROSS          NUMBER(14,2),
  NEW_GROSS          NUMBER(14,2),
  INCREASE_AMOUNT    NUMBER(14,2),
  INCREASE_PERCENT   NUMBER(8,2),
  REASON             VARCHAR2(1000 BYTE),
  REMARKS            VARCHAR2(1000 BYTE),
  SIGNATORY_ID       NUMBER,
  APPROVAL_STATUS    VARCHAR2(20 BYTE)          DEFAULT 'DRAFT'               NOT NULL,
  PROPOSED_BY        NUMBER,
  PROPOSED_DATE      DATE                       DEFAULT SYSDATE,
  CHECKED_BY         NUMBER,
  CHECKED_DATE       DATE,
  APPROVED_BY        NUMBER,
  APPROVED_DATE      DATE,
  POSTED_BY          NUMBER,
  POSTED_DATE        DATE,
  ENT_BY             NUMBER,
  ENT_DATE           DATE                       DEFAULT SYSDATE,
  UPD_BY             NUMBER,
  UPD_DATE           DATE
);


ALTER TABLE HR_EMPLOYEE_PROMOTION ADD (
  CONSTRAINT CHK_HR_EMP_PROMO_SALARY
  CHECK (new_basic >= 0)
  ENABLE VALIDATE
,  CONSTRAINT CHK_HR_EMP_PROMO_STATUS
  CHECK (approval_status IN ('DRAFT', 'SUBMITTED', 'CHECKED', 'APPROVED', 'POSTED', 'CANCELLED'))
  ENABLE VALIDATE
,  CONSTRAINT CHK_HR_EMP_PROMO_TYPE
  CHECK (promotion_type IN ('REGULAR', 'ACCELERATED'))
  ENABLE VALIDATE
,  PRIMARY KEY
  (PROMOTION_ID)
,  CONSTRAINT UK_HR_EMP_PROMOTION_NO
  UNIQUE (PROMOTION_NO)
  );

CREATE SEQUENCE HR_PROMOTION_NO_SEQ
  START WITH 141
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


CREATE OR REPLACE TRIGGER trg_hr_emp_promotion_no
    BEFORE INSERT
    ON hr_employee_promotion
    FOR EACH ROW
BEGIN
    IF :new.promotion_no IS NULL
    THEN
        :new.promotion_no :=
               'PRO-'
            || TO_CHAR (NVL (:new.effective_date, SYSDATE), 'YYYY')
            || '-'
            || LPAD (hr_promotion_no_seq.NEXTVAL, 6, '0');
    END IF;
END;
/


ALTER TABLE HR_EMPLOYEE_PROMOTION ADD (
  FOREIGN KEY (EMP_ID) 
  REFERENCES EMPLOYEES (ID)
  ENABLE VALIDATE);


