CREATE TABLE HR_PROMOTION_SALARY_DTL
(
  PROMO_SALARY_ID  NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 181 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  PROMOTION_ID     NUMBER                       NOT NULL,
  EMP_ID           NUMBER                       NOT NULL,
  SLNO             NUMBER                       NOT NULL,
  HEADCODE         VARCHAR2(20 BYTE),
  HEAD_NAME        VARCHAR2(100 BYTE),
  AMOUNT           NUMBER(12,2)                 DEFAULT 0,
  REVISION_TYPE    VARCHAR2(1 BYTE)             DEFAULT 'P',
  IS_POSTED        VARCHAR2(1 BYTE)             DEFAULT 'N',
  CREATED_BY       VARCHAR2(100 BYTE),
  CREATED_DATE     DATE                         DEFAULT SYSDATE,
  POSTED_BY        VARCHAR2(100 BYTE),
  POSTED_DATE      DATE
);


ALTER TABLE HR_PROMOTION_SALARY_DTL ADD (
  CONSTRAINT CHK_PROMO_SALARY_POSTED
  CHECK (is_posted IN ('Y','N'))
  ENABLE VALIDATE
,  PRIMARY KEY
  (PROMO_SALARY_ID));

ALTER TABLE HR_PROMOTION_SALARY_DTL ADD (
  CONSTRAINT FK_PROMO_SALARY_EMP 
  FOREIGN KEY (EMP_ID) 
  REFERENCES EMPLOYEES (ID)
  ENABLE VALIDATE
,  CONSTRAINT FK_PROMO_SALARY_PROMO 
  FOREIGN KEY (PROMOTION_ID) 
  REFERENCES HR_EMPLOYEE_PROMOTION (PROMOTION_ID)
  ENABLE VALIDATE);
