/* ============================================================================
   CONTRACT RENEWAL - CORE TABLES

   Pages using these objects:
     520 - Contract Renewal List
     521 - Contract Renewal Entry and Approval
     522 - Contract Renewal Letter

   Run as HRMS (or change the schema prefix). This is a new-install script.
   The letter configuration and package are installed by the next scripts.
   ============================================================================ */

CREATE TABLE HRMS.HR_EMPLOYEE_CONTRACT
(
    EMP_ID               NUMBER NOT NULL,
    CONTRACT_FROM_DATE   DATE NOT NULL,
    CONTRACT_TO_DATE     DATE NOT NULL,
    GRADE_ID             NUMBER,
    SCALE_ID             NUMBER,
    STEP_NO              NUMBER(3),
    LATEST_RENEWAL_ID    NUMBER,
    CONTRACT_STATUS      VARCHAR2(20 BYTE) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_BY           NUMBER,
    CREATED_DATE         DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_BY           NUMBER,
    UPDATED_DATE         DATE,
    CONSTRAINT PK_HR_EMP_CONTRACT PRIMARY KEY (EMP_ID),
    CONSTRAINT FK_HR_EMP_CONTRACT_EMP FOREIGN KEY (EMP_ID)
        REFERENCES HRMS.EMPLOYEES (ID),
    CONSTRAINT FK_HR_EMP_CONTRACT_GRADE FOREIGN KEY (GRADE_ID)
        REFERENCES HRMS.JOB_GRADES (ID),
    CONSTRAINT FK_HR_EMP_CONTRACT_SCALE FOREIGN KEY (SCALE_ID)
        REFERENCES HRMS.PAY_SCALE_MASTER (SCALE_ID),
    CONSTRAINT CK_HR_EMP_CONTRACT_DATES CHECK
        (CONTRACT_TO_DATE >= CONTRACT_FROM_DATE),
    CONSTRAINT CK_HR_EMP_CONTRACT_STATUS CHECK
        (CONTRACT_STATUS IN ('ACTIVE', 'EXPIRED', 'CLOSED')),
    CONSTRAINT CK_HR_EMP_CONTRACT_STEP CHECK
        (STEP_NO IS NULL OR STEP_NO BETWEEN 0 AND 25)
);

CREATE INDEX HRMS.IX_HR_EMP_CONTRACT_DUE
    ON HRMS.HR_EMPLOYEE_CONTRACT (CONTRACT_STATUS, CONTRACT_TO_DATE);


CREATE TABLE HRMS.HR_CONTRACT_RENEWAL
(
    RENEWAL_ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RENEWAL_NO            VARCHAR2(30 BYTE) NOT NULL,
    EMP_ID                NUMBER NOT NULL,
    ACTION_ID             NUMBER,
    LETTER_ID             NUMBER,

    EMP_CODE_SNAPSHOT     VARCHAR2(30 CHAR) NOT NULL,
    EMP_NAME_SNAPSHOT     VARCHAR2(200 CHAR) NOT NULL,
    DESIGNATION_SNAPSHOT  VARCHAR2(150 CHAR),
    DEPARTMENT_SNAPSHOT   VARCHAR2(150 CHAR),
    LOCATION_SNAPSHOT     VARCHAR2(150 CHAR),
    ADDRESS_SNAPSHOT      VARCHAR2(500 CHAR),
    COMPANY_SNAPSHOT      VARCHAR2(200 CHAR),
    GRADE_SNAPSHOT        VARCHAR2(100 CHAR),
    PAY_SCALE_SNAPSHOT    VARCHAR2(300 CHAR),

    CURRENT_FROM_DATE     DATE NOT NULL,
    CURRENT_TO_DATE       DATE NOT NULL,
    NEW_FROM_DATE         DATE NOT NULL,
    NEW_TO_DATE           DATE NOT NULL,

    OLD_GRADE_ID          NUMBER,
    NEW_GRADE_ID          NUMBER NOT NULL,
    OLD_SCALE_ID          NUMBER,
    NEW_SCALE_ID          NUMBER NOT NULL,
    OLD_STEP_NO           NUMBER(3),
    NEW_STEP_NO           NUMBER(3) NOT NULL,

    OLD_BASIC             NUMBER(14,2),
    NEW_BASIC             NUMBER(14,2),
    OLD_GROSS             NUMBER(14,2),
    NEW_GROSS             NUMBER(14,2),

    REASON                VARCHAR2(1000 CHAR),
    REMARKS               VARCHAR2(1000 CHAR),
    SPECIAL_TERMS         CLOB,
    SIGNATORY_ID          NUMBER,
    TEMPLATE_ID           NUMBER,
    APPROVAL_STATUS       VARCHAR2(20 BYTE) DEFAULT 'DRAFT' NOT NULL,
    VERSION_NO            NUMBER DEFAULT 0 NOT NULL,

    PREPARED_BY           NUMBER,
    PREPARED_DATE         DATE DEFAULT SYSDATE NOT NULL,
    SUBMITTED_BY          NUMBER,
    SUBMITTED_DATE        DATE,
    APPROVED_BY           NUMBER,
    APPROVED_DATE         DATE,
    POSTED_BY             NUMBER,
    POSTED_DATE           DATE,
    CANCELLED_BY          NUMBER,
    CANCELLED_DATE        DATE,
    CREATED_BY            NUMBER,
    CREATED_DATE          DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_BY            NUMBER,
    UPDATED_DATE          DATE,

    CONSTRAINT UK_HR_CONTRACT_RENEWAL_NO UNIQUE (RENEWAL_NO),
    CONSTRAINT FK_HR_CON_RENEW_EMP FOREIGN KEY (EMP_ID)
        REFERENCES HRMS.EMPLOYEES (ID),
    CONSTRAINT FK_HR_CON_RENEW_OLD_GRADE FOREIGN KEY (OLD_GRADE_ID)
        REFERENCES HRMS.JOB_GRADES (ID),
    CONSTRAINT FK_HR_CON_RENEW_NEW_GRADE FOREIGN KEY (NEW_GRADE_ID)
        REFERENCES HRMS.JOB_GRADES (ID),
    CONSTRAINT FK_HR_CON_RENEW_OLD_SCALE FOREIGN KEY (OLD_SCALE_ID)
        REFERENCES HRMS.PAY_SCALE_MASTER (SCALE_ID),
    CONSTRAINT FK_HR_CON_RENEW_NEW_SCALE FOREIGN KEY (NEW_SCALE_ID)
        REFERENCES HRMS.PAY_SCALE_MASTER (SCALE_ID),
    CONSTRAINT FK_HR_CON_RENEW_TEMPLATE FOREIGN KEY (TEMPLATE_ID)
        REFERENCES HRMS.HR_LETTER_TEMPLATE (TEMPLATE_ID),
    CONSTRAINT CK_HR_CON_RENEW_CUR_DATES CHECK
        (CURRENT_TO_DATE >= CURRENT_FROM_DATE),
    CONSTRAINT CK_HR_CON_RENEW_NEW_DATES CHECK
        (NEW_TO_DATE >= NEW_FROM_DATE),
    CONSTRAINT CK_HR_CON_RENEW_STEPS CHECK
        ((OLD_STEP_NO IS NULL OR OLD_STEP_NO BETWEEN 0 AND 25)
         AND NEW_STEP_NO BETWEEN 0 AND 25),
    CONSTRAINT CK_HR_CON_RENEW_STATUS CHECK
        (APPROVAL_STATUS IN
            ('DRAFT', 'SUBMITTED', 'APPROVED', 'POSTED', 'CANCELLED'))
);

CREATE SEQUENCE HRMS.HR_CONTRACT_RENEWAL_NO_SEQ
    START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;

CREATE OR REPLACE TRIGGER HRMS.TRG_HR_CONTRACT_RENEWAL_NO
    BEFORE INSERT ON HRMS.HR_CONTRACT_RENEWAL
    FOR EACH ROW
BEGIN
    IF :NEW.RENEWAL_NO IS NULL THEN
        :NEW.RENEWAL_NO :=
               'CRN-'
            || TO_CHAR(NVL(:NEW.NEW_FROM_DATE, SYSDATE), 'YYYY')
            || '-'
            || LPAD(HRMS.HR_CONTRACT_RENEWAL_NO_SEQ.NEXTVAL, 6, '0');
    END IF;
END;
/

/* Only one unfinished renewal may exist for an employee. */
CREATE UNIQUE INDEX HRMS.UX_HR_CON_RENEW_OPEN_EMP
    ON HRMS.HR_CONTRACT_RENEWAL
       (CASE
            WHEN APPROVAL_STATUS IN ('DRAFT', 'SUBMITTED', 'APPROVED')
            THEN EMP_ID
        END);

CREATE INDEX HRMS.IX_HR_CON_RENEW_EMP_STATUS
    ON HRMS.HR_CONTRACT_RENEWAL (EMP_ID, APPROVAL_STATUS, NEW_FROM_DATE);

CREATE INDEX HRMS.IX_HR_CON_RENEW_STATUS_DATE
    ON HRMS.HR_CONTRACT_RENEWAL (APPROVAL_STATUS, NEW_FROM_DATE);


CREATE TABLE HRMS.HR_CONTRACT_RENEWAL_SALARY
(
    RENEWAL_SALARY_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RENEWAL_ID          NUMBER NOT NULL,
    EMP_ID              NUMBER NOT NULL,
    SALS_ID             NUMBER,
    SLNO                NUMBER NOT NULL,
    HEADCODE            VARCHAR2(20 BYTE) NOT NULL,
    HEAD_NAME           VARCHAR2(100 CHAR),
    HEAD_TYPE           VARCHAR2(10 BYTE),
    PRINT_ORDER         NUMBER(4),
    OLD_AMOUNT          NUMBER(14,2) DEFAULT 0 NOT NULL,
    NEW_AMOUNT          NUMBER(14,2) DEFAULT 0 NOT NULL,
    INCLUDE_IN_LETTER   VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL,
    IS_POSTED           VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
    CREATED_BY          NUMBER,
    CREATED_DATE        DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_BY          NUMBER,
    UPDATED_DATE        DATE,
    POSTED_BY           NUMBER,
    POSTED_DATE         DATE,
    CONSTRAINT FK_HR_CON_REN_SAL_RENEW FOREIGN KEY (RENEWAL_ID)
        REFERENCES HRMS.HR_CONTRACT_RENEWAL (RENEWAL_ID) ON DELETE CASCADE,
    CONSTRAINT FK_HR_CON_REN_SAL_EMP FOREIGN KEY (EMP_ID)
        REFERENCES HRMS.EMPLOYEES (ID),
    CONSTRAINT UK_HR_CON_REN_SAL_HEAD UNIQUE (RENEWAL_ID, SLNO),
    CONSTRAINT CK_HR_CON_REN_SAL_AMOUNT CHECK
        (OLD_AMOUNT >= 0 AND NEW_AMOUNT >= 0),
    CONSTRAINT CK_HR_CON_REN_SAL_PRINT CHECK
        (INCLUDE_IN_LETTER IN ('Y', 'N')),
    CONSTRAINT CK_HR_CON_REN_SAL_POST CHECK
        (IS_POSTED IN ('Y', 'N')),
    CONSTRAINT CK_HR_CON_REN_SAL_TYPE CHECK
        (HEAD_TYPE IS NULL OR HEAD_TYPE IN ('EARNING', 'DEDUCTION'))
);

CREATE INDEX HRMS.IX_HR_CON_REN_SAL_RENEW
    ON HRMS.HR_CONTRACT_RENEWAL_SALARY (RENEWAL_ID, PRINT_ORDER, SLNO);


CREATE TABLE HRMS.HR_CONTRACT_RENEWAL_AUDIT
(
    AUDIT_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RENEWAL_ID      NUMBER NOT NULL,
    EVENT_TYPE      VARCHAR2(30 BYTE) NOT NULL,
    FROM_STATUS     VARCHAR2(20 BYTE),
    TO_STATUS       VARCHAR2(20 BYTE),
    EVENT_REMARKS   VARCHAR2(1000 CHAR),
    EVENT_BY        NUMBER NOT NULL,
    EVENT_DATE      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_HR_CON_REN_AUD_RENEW FOREIGN KEY (RENEWAL_ID)
        REFERENCES HRMS.HR_CONTRACT_RENEWAL (RENEWAL_ID) ON DELETE CASCADE
);

CREATE INDEX HRMS.IX_HR_CON_REN_AUD_RENEW
    ON HRMS.HR_CONTRACT_RENEWAL_AUDIT (RENEWAL_ID, EVENT_DATE);

ALTER TABLE HRMS.HR_CONTRACT_RENEWAL ADD CONSTRAINT FK_HR_CON_RENEW_ACTION
    FOREIGN KEY (ACTION_ID) REFERENCES HRMS.HR_EMPLOYEE_ACTION (ACTION_ID);

ALTER TABLE HRMS.HR_EMPLOYEE_CONTRACT ADD CONSTRAINT FK_HR_EMP_CON_LATEST_REN
    FOREIGN KEY (LATEST_RENEWAL_ID)
    REFERENCES HRMS.HR_CONTRACT_RENEWAL (RENEWAL_ID);

COMMENT ON TABLE HRMS.HR_EMPLOYEE_CONTRACT IS
    'Current live contract term used by the Page 520 due list.';
COMMENT ON TABLE HRMS.HR_CONTRACT_RENEWAL IS
    'Contract renewal workflow header: draft, submit, approve, and final post.';
COMMENT ON TABLE HRMS.HR_CONTRACT_RENEWAL_SALARY IS
    'Immutable old salary snapshot plus proposed salary used by renewal posting and letter.';
COMMENT ON COLUMN HRMS.HR_CONTRACT_RENEWAL.APPROVAL_STATUS IS
    'DRAFT -> SUBMITTED -> APPROVED -> POSTED; CANCELLED is terminal.';
