DROP TABLE HRMS.ALLOWANCE_HEAD CASCADE CONSTRAINTS;

CREATE TABLE HRMS.ALLOWANCE_HEAD
(
  HEAD_ID       NUMBER,
  HEAD_CODE     VARCHAR2(20 BYTE)               NOT NULL,
  HEAD_NAME     VARCHAR2(100 BYTE)              NOT NULL,
  HEAD_TYPE     VARCHAR2(10 BYTE)               NOT NULL,
  CALC_TYPE     VARCHAR2(10 BYTE)               NOT NULL,
  IS_TAXABLE    VARCHAR2(1 BYTE)                DEFAULT 'Y',
  PRINT_ORDER   NUMBER(3),
  IS_ACTIVE     VARCHAR2(1 BYTE)                DEFAULT 'Y',
  REMARKS       VARCHAR2(200 BYTE),
  CREATED_BY    NUMBER,
  CREATED_DATE  DATE                            DEFAULT SYSDATE,
  UPDATED_BY    NUMBER,
  UPDATED_DATE  DATE,
  IS_ADV        VARCHAR2(3 BYTE)                DEFAULT 'N'
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.ALLOWANCE_HEAD_PK ON HRMS.ALLOWANCE_HEAD
(HEAD_ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX HRMS.UK_HEAD_CODE ON HRMS.ALLOWANCE_HEAD
(HEAD_CODE)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.ALLOWANCE_HEAD ADD (
  CONSTRAINT CHK_HEAD_ACTIVE
  CHECK (is_active IN ('Y', 'N'))
  ENABLE VALIDATE
,  CONSTRAINT CHK_HEAD_CALC
  CHECK (calc_type IN ('PERCENT', 'FIXED'))
  ENABLE VALIDATE
,  CONSTRAINT CHK_HEAD_TAXABLE
  CHECK (is_taxable IN ('Y', 'N'))
  ENABLE VALIDATE
,  CONSTRAINT CHK_HEAD_TYPE
  CHECK (head_type IN ('EARNING', 'DEDUCTION'))
  ENABLE VALIDATE
,  CONSTRAINT ALLOWANCE_HEAD_PK
  PRIMARY KEY
  (HEAD_ID)
  USING INDEX HRMS.ALLOWANCE_HEAD_PK
  ENABLE VALIDATE
,  CONSTRAINT UK_HEAD_CODE
  UNIQUE (HEAD_CODE)
  USING INDEX HRMS.UK_HEAD_CODE
  ENABLE VALIDATE);
