DROP TABLE HRMS.COMPANY CASCADE CONSTRAINTS;

CREATE TABLE HRMS.COMPANY
(
  ID        NUMBER,
  CODE      VARCHAR2(5 BYTE),
  NAME      VARCHAR2(50 BYTE),
  ADDRESS   VARCHAR2(100 BYTE),
  REG_NO    VARCHAR2(30 BYTE),
  BIN       VARCHAR2(30 BYTE),
  PHONE     VARCHAR2(30 BYTE),
  EMAIL     VARCHAR2(30 BYTE),
  ENT_BY    NUMBER,
  ENT_DATE  DATE,
  UPD_BY    NUMBER,
  UPD_DATE  DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.COMPANY_PK ON HRMS.COMPANY
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX HRMS.COMPANY_U01 ON HRMS.COMPANY
(CODE)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX HRMS.COMPANY_U02 ON HRMS.COMPANY
(BIN)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.COMPANY ADD (
  CONSTRAINT COMPANY_PK
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.COMPANY_PK
  ENABLE VALIDATE
,  CONSTRAINT COMPANY_U01
  UNIQUE (CODE)
  USING INDEX HRMS.COMPANY_U01
  ENABLE VALIDATE
,  CONSTRAINT COMPANY_U02
  UNIQUE (BIN)
  USING INDEX HRMS.COMPANY_U02
  ENABLE VALIDATE);


CREATE OR REPLACE TRIGGER HRMS.TRG_COMPANY_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.COMPANY
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM COMPANY;
    END IF;
END TRG_COMPANY_PK;
/
