DROP TABLE HRMS.DEPARTMENTS CASCADE CONSTRAINTS;

CREATE TABLE HRMS.DEPARTMENTS
(
  ID         NUMBER,
  DEPT_NAME  VARCHAR2(50 BYTE),
  ADDRESS    VARCHAR2(100 BYTE),
  COM_ID     NUMBER,
  ENT_BY     NUMBER,
  ENT_DATE   DATE,
  UPD_BY     NUMBER,
  UPD_DATE   DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.DEPARTMENTS_PK ON HRMS.DEPARTMENTS
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.DEPARTMENTS ADD (
  CONSTRAINT DEPARTMENTS_PK
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.DEPARTMENTS_PK
  ENABLE VALIDATE);


CREATE OR REPLACE TRIGGER HRMS.TRG_departments_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.DEPARTMENTS
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM departments;
    END IF;
END TRG_departments_PK;
/
