DROP TABLE HRMS.DESIGNATIONS CASCADE CONSTRAINTS;

CREATE TABLE HRMS.DESIGNATIONS
(
  ID           NUMBER,
  REFNO        VARCHAR2(30 BYTE),
  REFDATE      DATE,
  CODE         VARCHAR2(30 BYTE),
  DESIGNATION  VARCHAR2(100 BYTE),
  ENT_BY       NUMBER,
  ENT_DATE     DATE,
  UPD_BY       NUMBER,
  UPD_DATE     DATE,
  CATA         VARCHAR2(5 BYTE),
  GRADE        NUMBER,
  SL           NUMBER
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.DESIGNATIONS_PK ON HRMS.DESIGNATIONS
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.DESIGNATIONS ADD (
  CONSTRAINT DESIGNATIONS_PK
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.DESIGNATIONS_PK
  ENABLE VALIDATE);


CREATE OR REPLACE TRIGGER HRMS.trg_desig_pk
    BEFORE INSERT OR UPDATE
    ON HRMS.DESIGNATIONS
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM designations;
    END IF;
END trg_desig_pk;
/
