DROP TABLE HRMS.EMP_FAMILY_DTL CASCADE CONSTRAINTS;

CREATE TABLE HRMS.EMP_FAMILY_DTL
(
  ID        NUMBER,
  EMP_ID    NUMBER,
  RELATION  VARCHAR2(100 BYTE),
  NAME      VARCHAR2(100 BYTE),
  REMARKS   VARCHAR2(100 BYTE),
  ENT_BY    NUMBER,
  ENT_DATE  DATE,
  UPD_BY    NUMBER,
  UPD_DATE  DATE,
  DOB       DATE,
  AGE       VARCHAR2(50 BYTE),
  CONTACT   VARCHAR2(50 BYTE)
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.PK_EMP_FAMILY_DTL ON HRMS.EMP_FAMILY_DTL
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.EMP_FAMILY_DTL ADD (
  CONSTRAINT PK_EMP_FAMILY_DTL
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.PK_EMP_FAMILY_DTL
  ENABLE VALIDATE);


CREATE OR REPLACE TRIGGER HRMS.TRG_EMP_FAMILY_DTL_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.EMP_FAMILY_DTL
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM EMP_FAMILY_DTL;
    END IF;
END TRG_EMP_FAMILY_DTL_PK;
/


ALTER TABLE HRMS.EMP_FAMILY_DTL ADD (
  CONSTRAINT FK_EMP_ID_FAMILY_DTL 
  FOREIGN KEY (EMP_ID) 
  REFERENCES HRMS.EMPLOYEES (ID)
  ENABLE VALIDATE);
