DROP TABLE HRMS.EMP_TRAINING CASCADE CONSTRAINTS;

CREATE TABLE HRMS.EMP_TRAINING
(
  ID               NUMBER,
  EMP_ID           NUMBER,
  TRAINING_NAME    VARCHAR2(100 BYTE),
  INSTITUTION      VARCHAR2(100 BYTE),
  START_DATE       DATE,
  COMPLETION_DATE  DATE,
  DURATION         VARCHAR2(100 BYTE),
  REMARKS          VARCHAR2(100 BYTE),
  ENT_BY           NUMBER,
  ENT_DATE         DATE,
  UPD_BY           NUMBER,
  UPD_DATE         DATE,
  MIME_TYPE        VARCHAR2(200 BYTE),
  FILE_NAME        VARCHAR2(200 BYTE),
  UPD_AT           DATE                         DEFAULT SYSDATE,
  ATTACHMENT       BLOB,
  RESULT           VARCHAR2(30 BYTE),
  SESS             VARCHAR2(30 BYTE),
  TOPICS           VARCHAR2(200 BYTE),
  COUNTRY          VARCHAR2(50 BYTE)
)
LOB (ATTACHMENT) STORE AS SECUREFILE (
  TABLESPACE  HRMS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.PK_EMP_TRAINING ON HRMS.EMP_TRAINING
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.EMP_TRAINING ADD (
  CONSTRAINT PK_EMP_TRAINING
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.PK_EMP_TRAINING
  ENABLE VALIDATE);


CREATE OR REPLACE TRIGGER HRMS.TRG_EMP_TRAINING_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.EMP_TRAINING
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM EMP_TRAINING;
    END IF;
END TRG_EMP_TRAINING_PK;
/


ALTER TABLE HRMS.EMP_TRAINING ADD (
  CONSTRAINT FK_EMP_ID_TRAINING 
  FOREIGN KEY (EMP_ID) 
  REFERENCES HRMS.EMPLOYEES (ID)
  ENABLE VALIDATE);
