DROP TABLE HRMS.EMP_EDUCATION CASCADE CONSTRAINTS;

CREATE TABLE HRMS.EMP_EDUCATION
(
  ID            NUMBER,
  EMP_ID        NUMBER,
  EXAM          NUMBER,
  SUB_GROUP     NUMBER,
  PASSING_YEAR  NUMBER(4),
  DURATION      NUMBER,
  BOARD         NUMBER,
  REMARKS       VARCHAR2(100 BYTE),
  ENT_BY        NUMBER,
  ENT_DATE      DATE,
  UPD_BY        NUMBER,
  UPD_DATE      DATE,
  MIME_TYPE     VARCHAR2(200 BYTE),
  FILE_NAME     VARCHAR2(200 BYTE),
  UPD_AT        DATE                            DEFAULT SYSDATE,
  ATTACHMENT    BLOB,
  SLNO          NUMBER,
  EMPCODE       VARCHAR2(50 BYTE),
  EXAMGROUP     VARCHAR2(70 BYTE),
  BOARD_N       VARCHAR2(100 BYTE),
  CLAS          VARCHAR2(30 BYTE),
  PASSYEAR      VARCHAR2(10 BYTE),
  INSTITUTE     VARCHAR2(50 BYTE),
  SUBJECT_NAME  VARCHAR2(200 BYTE),
  EXAMNAME      VARCHAR2(70 BYTE),
  BACHELORS     VARCHAR2(200 BYTE),
  CGPA          VARCHAR2(30 BYTE)
)
LOB (ATTACHMENT) STORE AS SECUREFILE (
  TABLESPACE  HRMS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.PK_EMP_EDUCATION ON HRMS.EMP_EDUCATION
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.EMP_EDUCATION ADD (
  CONSTRAINT PK_EMP_EDUCATION
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.PK_EMP_EDUCATION
  ENABLE VALIDATE);


CREATE OR REPLACE TRIGGER HRMS.TRG_EMP_EDUCATION_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.EMP_EDUCATION
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM emp_education;
    END IF;
END trg_emp_education_pk;
/


ALTER TABLE HRMS.EMP_EDUCATION ADD (
  CONSTRAINT FK_EMP_EDUCATION 
  FOREIGN KEY (EMP_ID) 
  REFERENCES HRMS.EMPLOYEES (ID)
  ENABLE VALIDATE);
