DROP TABLE HRMS.EMP_EXPERIENCE CASCADE CONSTRAINTS;

CREATE TABLE HRMS.EMP_EXPERIENCE
(
  ID            NUMBER,
  EMP_ID        NUMBER,
  COMPANY_NAME  VARCHAR2(100 BYTE),
  JOB_TITLE     VARCHAR2(100 BYTE),
  JOB_DES       VARCHAR2(100 BYTE),
  START_DATE    DATE,
  END_DATE      DATE,
  DURATION      VARCHAR2(100 BYTE),
  REMARKS       VARCHAR2(100 BYTE),
  ENT_BY        NUMBER,
  ENT_DATE      DATE,
  UPD_BY        NUMBER,
  UPD_DATE      DATE,
  MIME_TYPE     VARCHAR2(200 BYTE),
  FILE_NAME     VARCHAR2(200 BYTE),
  UPD_AT        DATE                            DEFAULT SYSDATE,
  ATTACHMENT    BLOB
)
LOB (ATTACHMENT) STORE AS SECUREFILE (
  TABLESPACE  HRMS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.PK_EMP_ID_EXPERIENCE ON HRMS.EMP_EXPERIENCE
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.EMP_EXPERIENCE ADD (
  CONSTRAINT PK_EMP_ID_EXPERIENCE
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.PK_EMP_ID_EXPERIENCE
  ENABLE VALIDATE);


CREATE OR REPLACE TRIGGER HRMS.TRG_EMP_EXPERIENCE_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.EMP_EXPERIENCE
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM EMP_EXPERIENCE;
    END IF;
END TRG_EMP_EXPERIENCE_PK;
/


ALTER TABLE HRMS.EMP_EXPERIENCE ADD (
  CONSTRAINT FK_EMP_ID_EXPERIENCE 
  FOREIGN KEY (EMP_ID) 
  REFERENCES HRMS.EMPLOYEES (ID)
  ENABLE VALIDATE);
