DROP TABLE HRMS.EMP_EMERGENCY_CONTACT CASCADE CONSTRAINTS;

CREATE TABLE HRMS.EMP_EMERGENCY_CONTACT
(
  ID           NUMBER,
  EMP_ID       NUMBER,
  CONT_PERSON  VARCHAR2(50 BYTE),
  CONTACT      VARCHAR2(30 BYTE),
  ALT_CONT     VARCHAR2(30 BYTE),
  ENT_BY       NUMBER,
  ENT_DATE     DATE,
  UPD_BY       NUMBER,
  UPD_DATE     DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.EMP_EMERGENCY_CONTACT_PK ON HRMS.EMP_EMERGENCY_CONTACT
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.EMP_EMERGENCY_CONTACT ADD (
  CONSTRAINT EMP_EMERGENCY_CONTACT_PK
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.EMP_EMERGENCY_CONTACT_PK
  ENABLE VALIDATE);
