DROP TABLE HRMS.EXAMS CASCADE CONSTRAINTS;

CREATE TABLE HRMS.EXAMS
(
  ID        NUMBER,
  NAME      VARCHAR2(100 BYTE),
  ENT_BY    NUMBER,
  ENT_DATE  DATE,
  UPD_BY    NUMBER,
  UPD_DATE  DATE,
  TYP       VARCHAR2(10 BYTE)
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.EXAMS_PK ON HRMS.EXAMS
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX HRMS.EXAMS_U01 ON HRMS.EXAMS
(NAME)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.EXAMS ADD (
  CONSTRAINT EXAMS_PK
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.EXAMS_PK
  ENABLE VALIDATE
,  CONSTRAINT EXAMS_U01
  UNIQUE (NAME)
  USING INDEX HRMS.EXAMS_U01
  ENABLE VALIDATE);


CREATE OR REPLACE TRIGGER HRMS.trg_exams_pk
    BEFORE INSERT OR UPDATE
    ON HRMS.EXAMS
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM exams;
    END IF;
END trg_exams_pk;
/
