DROP TABLE HRMS.GRADE_ALLOWANCE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE HRMS.GRADE_ALLOWANCE_DETAIL
(
  GA_ID         NUMBER,
  SCALE_ID      NUMBER                          NOT NULL,
  HEAD_ID       NUMBER                          NOT NULL,
  CALC_VALUE    NUMBER(10,2)                    NOT NULL,
  MIN_AMOUNT    NUMBER(10,2),
  MAX_AMOUNT    NUMBER(10,2),
  IS_ACTIVE     VARCHAR2(1 BYTE)                DEFAULT 'Y',
  REMARKS       VARCHAR2(500 BYTE),
  CREATED_BY    NUMBER,
  CREATED_DATE  DATE                            DEFAULT SYSDATE,
  UPDATED_BY    NUMBER,
  UPDATED_DATE  DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.UK_SCALE_HEAD ON HRMS.GRADE_ALLOWANCE_DETAIL
(SCALE_ID, HEAD_ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.GRADE_ALLOWANCE_DETAIL ADD (
  CONSTRAINT CHK_GA_ACTIVE
  CHECK (is_active IN ('Y', 'N'))
  ENABLE VALIDATE
,  CONSTRAINT UK_SCALE_HEAD
  UNIQUE (SCALE_ID, HEAD_ID)
  USING INDEX HRMS.UK_SCALE_HEAD
  ENABLE VALIDATE);


CREATE INDEX HRMS.IDX_GA_HEAD ON HRMS.GRADE_ALLOWANCE_DETAIL
(HEAD_ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX HRMS.IDX_GA_SCALE ON HRMS.GRADE_ALLOWANCE_DETAIL
(SCALE_ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.GRADE_ALLOWANCE_DETAIL ADD (
  CONSTRAINT FK_GA_HEAD 
  FOREIGN KEY (HEAD_ID) 
  REFERENCES HRMS.ALLOWANCE_HEAD (HEAD_ID)
  ENABLE VALIDATE
,  CONSTRAINT FK_GA_SCALE 
  FOREIGN KEY (SCALE_ID) 
  REFERENCES HRMS.PAY_SCALE_MASTER (SCALE_ID)
  ENABLE VALIDATE);
