DROP TABLE HRMS.HR_ADV_INSTALLMENTS CASCADE CONSTRAINTS;

CREATE TABLE HRMS.HR_ADV_INSTALLMENTS
(
  INSTALLMENT_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 40821 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  ADV_ID              NUMBER                    NOT NULL,
  INSTALLMENT_NO      NUMBER                    NOT NULL,
  PERIOD_ID           NUMBER,
  DUE_DATE            DATE,
  INSTALLMENT_AMOUNT  NUMBER(14,2)              NOT NULL,
  PAID_AMOUNT         NUMBER(14,2)              DEFAULT 0,
  WAIVED_AMOUNT       NUMBER(14,2)              DEFAULT 0,
  STATUS              VARCHAR2(20 BYTE)         DEFAULT 'PENDING',
  PAID_DATE           DATE,
  PAYROLL_RUN_ID      NUMBER,
  REMARKS             VARCHAR2(1000 BYTE),
  CREATED_BY          VARCHAR2(100 BYTE)        DEFAULT USER,
  CREATED_DATE        DATE                      DEFAULT SYSDATE,
  UPDATED_BY          VARCHAR2(100 BYTE),
  UPDATED_DATE        DATE,
  YEARMN              NUMBER
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.HR_ADV_INST_UK ON HRMS.HR_ADV_INSTALLMENTS
(ADV_ID, INSTALLMENT_NO)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.HR_ADV_INSTALLMENTS ADD (
  CONSTRAINT HR_ADV_INST_CK_STATUS
  CHECK (STATUS IN (
            'PENDING',
            'PARTIAL',
            'PAID',
            'HOLD',
            'SKIPPED',
            'WAIVED',
            'CANCELLED'
        ))
  ENABLE VALIDATE
,  PRIMARY KEY
  (INSTALLMENT_ID)
  USING INDEX
    TABLESPACE HRMS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE
,  CONSTRAINT HR_ADV_INST_UK
  UNIQUE (ADV_ID, INSTALLMENT_NO)
  USING INDEX HRMS.HR_ADV_INST_UK
  ENABLE VALIDATE);


DROP SEQUENCE HRMS.ISEQ$$_222913;

-- Sequence ISEQ$$_222913 is created automatically by Oracle for use with an Identity column


--  There is no statement for index HRMS.SYS_C0024685.
--  The object is created when the parent object is created.
