DROP TABLE HRMS.HR_EMPLOYEE_ACTION CASCADE CONSTRAINTS;

CREATE TABLE HRMS.HR_EMPLOYEE_ACTION
(
  ACTION_ID          NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 4961 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  EMP_ID             NUMBER                     NOT NULL,
  INCREMENT_ID       NUMBER,
  ACTION_TYPE        VARCHAR2(30 BYTE)          NOT NULL,
  ACTION_DATE        DATE                       DEFAULT SYSDATE               NOT NULL,
  EFFECTIVE_DATE     DATE                       NOT NULL,
  OLD_EFFECTIVE_DATE DATE,
  NEW_EFFECTIVE_DATE DATE,
  REVERSAL_OF_ACTION_ID NUMBER,
  OLD_EMP_TYPE_ID    NUMBER,
  NEW_EMP_TYPE_ID    NUMBER,
  OLD_JOB_ID         NUMBER,
  NEW_JOB_ID         NUMBER,
  OLD_DESIG_ID       NUMBER,
  NEW_DESIG_ID       NUMBER,
  OLD_DEPT_ID        NUMBER,
  NEW_DEPT_ID        NUMBER,
  OLD_BASIC          NUMBER(14,2),
  NEW_BASIC          NUMBER(14,2),
  OLD_GROSS          NUMBER(14,2),
  NEW_GROSS          NUMBER(14,2),
  INCREMENT_AMOUNT   NUMBER(14,2),
  INCREMENT_PERCENT  NUMBER(8,2),
  OLD_EB_STATUS      VARCHAR2(20 BYTE),
  NEW_EB_STATUS      VARCHAR2(20 BYTE),
  REASON             VARCHAR2(1000 BYTE),
  REMARKS            VARCHAR2(1000 BYTE),
  APPROVAL_STATUS    VARCHAR2(20 BYTE)          DEFAULT 'DRAFT',
  ENT_BY             NUMBER,
  ENT_DATE           DATE                       DEFAULT SYSDATE,
  UPD_BY             NUMBER,
  UPD_DATE           DATE,
  APPROVED_BY        NUMBER,
  APPROVED_DATE      DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


ALTER TABLE HRMS.HR_EMPLOYEE_ACTION ADD (
  PRIMARY KEY
  (ACTION_ID)
  USING INDEX
    TABLESPACE HRMS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);


DROP SEQUENCE HRMS.ISEQ$$_226098;

-- Sequence ISEQ$$_226098 is created automatically by Oracle for use with an Identity column


--  There is no statement for index HRMS.SYS_C0024988.
--  The object is created when the parent object is created.

CREATE INDEX HRMS.IDX_HR_EMP_ACTION_INCREMENT
    ON HRMS.HR_EMPLOYEE_ACTION (INCREMENT_ID, ACTION_TYPE);

CREATE INDEX HRMS.IDX_HR_EMP_ACTION_EMP_DATE
    ON HRMS.HR_EMPLOYEE_ACTION (EMP_ID, EFFECTIVE_DATE, ACTION_TYPE);

CREATE INDEX HRMS.IDX_HR_EMP_ACTION_REVERSAL
    ON HRMS.HR_EMPLOYEE_ACTION (REVERSAL_OF_ACTION_ID);
