DROP TABLE HRMS.HR_EMPLOYEE_INCREMENT CASCADE CONSTRAINTS;

CREATE TABLE HRMS.HR_EMPLOYEE_INCREMENT
(
  INCREMENT_ID            NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
  EMP_ID                  NUMBER                        NOT NULL,
  COM_ID                  NUMBER                        NOT NULL,
  ORIGINAL_LIST_DATE      DATE                          NOT NULL,
  CURRENT_LIST_DATE       DATE                          NOT NULL,
  SALARY_MONTH            NUMBER(6)                     NOT NULL,
  DUE_DATE                DATE                          NOT NULL,
  EFFECTIVE_DATE          DATE                          NOT NULL,
  REVISED_EFFECTIVE_DATE  DATE,
  OLD_BASIC               NUMBER(14,2)                  DEFAULT 0 NOT NULL,
  PROPOSED_BASIC          NUMBER(14,2)                  DEFAULT 0 NOT NULL,
  OLD_GROSS               NUMBER(14,2)                  DEFAULT 0 NOT NULL,
  PROPOSED_GROSS          NUMBER(14,2),
  INCREMENT_AMOUNT        NUMBER(14,2)                  DEFAULT 0 NOT NULL,
  SCALE_ID                NUMBER,
  FROM_STEP_NO            NUMBER(3),
  TO_STEP_NO              NUMBER(3),
  TOTAL_STEPS             NUMBER(3)                     DEFAULT 25,
  DECISION_CODE           VARCHAR2(30),
  HOLD_TYPE               VARCHAR2(30),
  HOLD_REASON             VARCHAR2(1000),
  HOLD_REVIEW_DATE        DATE,
  PUNISHMENT_REF_NO       VARCHAR2(100),
  STATUS                  VARCHAR2(30)                  DEFAULT 'DRAFT' NOT NULL,
  ACTION_ID               NUMBER,
  REVERSE_ACTION_ID       NUMBER,
  REVERSED_BY             NUMBER,
  REVERSED_DATE           DATE,
  REVERSAL_REASON         VARCHAR2(1000),
  CHANGE_REASON           VARCHAR2(1000),
  REMARKS                 VARCHAR2(1000),
  CREATED_BY              NUMBER,
  CREATED_DATE            DATE                          DEFAULT SYSDATE NOT NULL,
  UPDATED_BY              NUMBER,
  UPDATED_DATE            DATE,
  POSTED_BY               NUMBER,
  POSTED_DATE             DATE,
  VERSION_NO              NUMBER                        DEFAULT 1 NOT NULL,

  CONSTRAINT PK_HR_EMPLOYEE_INCREMENT
    PRIMARY KEY (INCREMENT_ID),

  CONSTRAINT UK_HR_EMP_INC_OCCURRENCE
    UNIQUE (EMP_ID, DUE_DATE),

  CONSTRAINT FK_HR_EMP_INC_EMP
    FOREIGN KEY (EMP_ID) REFERENCES HRMS.EMPLOYEES (ID),

  CONSTRAINT FK_HR_EMP_INC_COMPANY
    FOREIGN KEY (COM_ID) REFERENCES HRMS.COMPANY (ID),

  CONSTRAINT FK_HR_EMP_INC_SCALE
    FOREIGN KEY (SCALE_ID) REFERENCES HRMS.PAY_SCALE_MASTER (SCALE_ID),

  CONSTRAINT CHK_HR_EMP_INC_STATUS
    CHECK (STATUS IN (
      'DRAFT', 'READY', 'EXTENDED', 'HOLD', 'PUNISHMENT',
      'FORFEITED', 'POSTED', 'CANCELLED', 'ERROR', 'REVERSED',
      'CLOSED_NO_INCREMENT'
    )),

  CONSTRAINT CHK_HR_EMP_INC_DECISION
    CHECK (DECISION_CODE IS NULL OR DECISION_CODE IN (
      'READY', 'TEMP_HOLD', 'PUNISHMENT_DELAY', 'PUNISHMENT_FORFEIT',
      'EB_HOLD', 'MAX_REACHED'
    )),

  CONSTRAINT CHK_HR_EMP_INC_HOLD_TYPE
    CHECK (HOLD_TYPE IS NULL OR HOLD_TYPE IN (
      'TEMP_HOLD', 'PUNISHMENT_DELAY', 'PUNISHMENT_FORFEIT'
    )),

  CONSTRAINT CHK_HR_EMP_INC_DATES
    CHECK (
      CURRENT_LIST_DATE >= ORIGINAL_LIST_DATE
      AND ORIGINAL_LIST_DATE = TRUNC(ORIGINAL_LIST_DATE, 'MM')
      AND CURRENT_LIST_DATE = TRUNC(CURRENT_LIST_DATE, 'MM')
      AND DUE_DATE = TRUNC(DUE_DATE)
      AND EFFECTIVE_DATE = TRUNC(EFFECTIVE_DATE)
      AND EFFECTIVE_DATE = DUE_DATE
      AND (REVISED_EFFECTIVE_DATE IS NULL
           OR REVISED_EFFECTIVE_DATE > EFFECTIVE_DATE)
    ),

  CONSTRAINT CHK_HR_EMP_INC_STEPS
    CHECK (
      TOTAL_STEPS = 25
      AND (FROM_STEP_NO IS NULL OR FROM_STEP_NO BETWEEN 0 AND 25)
      AND (TO_STEP_NO IS NULL OR TO_STEP_NO BETWEEN 0 AND 25)
    ),

  CONSTRAINT CHK_HR_EMP_INC_AMOUNTS
    CHECK (
      OLD_BASIC >= 0
      AND PROPOSED_BASIC >= 0
      AND OLD_GROSS >= 0
      AND INCREMENT_AMOUNT >= 0
    )
);

CREATE INDEX HRMS.IDX_HR_EMP_INC_WORKLIST
    ON HRMS.HR_EMPLOYEE_INCREMENT
       (COM_ID, CURRENT_LIST_DATE, STATUS, DECISION_CODE);

CREATE INDEX HRMS.IDX_HR_EMP_INC_EMP_DATE
    ON HRMS.HR_EMPLOYEE_INCREMENT
       (EMP_ID, DUE_DATE DESC);

CREATE INDEX HRMS.IDX_HR_EMP_INC_SAL_MONTH
    ON HRMS.HR_EMPLOYEE_INCREMENT
       (SALARY_MONTH, COM_ID, STATUS);

CREATE INDEX HRMS.IDX_HR_EMP_INC_ACTION
    ON HRMS.HR_EMPLOYEE_INCREMENT
       (ACTION_ID);

CREATE INDEX HRMS.IDX_HR_EMP_INC_REVERSE_ACTION
    ON HRMS.HR_EMPLOYEE_INCREMENT
       (REVERSE_ACTION_ID);
