DROP TABLE HRMS.HR_EMPFAMILYDET CASCADE CONSTRAINTS;

CREATE TABLE HRMS.HR_EMPFAMILYDET
(
  SLNO        NUMBER,
  EMPCODE     VARCHAR2(50 BYTE),
  FAMILYDES   VARCHAR2(50 BYTE),
  FNAME       VARCHAR2(100 BYTE),
  F_AGE       VARCHAR2(30 BYTE),
  F_OCUP      VARCHAR2(70 BYTE),
  F_ADD       VARCHAR2(100 BYTE),
  PHONE       VARCHAR2(25 BYTE),
  CHILD_NOS   NUMBER,
  BIRTH_DATE  DATE,
  USERNAME    VARCHAR2(100 BYTE)
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;
