DROP TABLE HRMS.HR_INCREMENT_HOLD CASCADE CONSTRAINTS;

CREATE TABLE HRMS.HR_INCREMENT_HOLD
(
  HOLD_ID          NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 21 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  EMP_ID           NUMBER                       NOT NULL,
  INCREMENT_ID     NUMBER                       NOT NULL,
  HOLD_FROM_DATE   DATE                         DEFAULT SYSDATE,
  HOLD_TO_DATE     DATE,
  HOLD_REASON      VARCHAR2(1000 BYTE),
  HOLD_STATUS      VARCHAR2(20 BYTE)            DEFAULT 'ACTIVE',
  RELEASED_DATE    DATE,
  RELEASED_BY      NUMBER,
  RELEASE_REMARKS  VARCHAR2(1000 BYTE),
  ACTION_ID        NUMBER,
  ENT_BY           NUMBER,
  ENT_DATE         DATE                         DEFAULT SYSDATE,
  UPD_BY           NUMBER,
  UPD_DATE         DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


ALTER TABLE HRMS.HR_INCREMENT_HOLD ADD (
  CONSTRAINT CHK_HR_INC_HOLD_STATUS
  CHECK (HOLD_STATUS IN ('ACTIVE','RELEASED','CANCELLED'))
  ENABLE VALIDATE
, CONSTRAINT FK_HR_INC_HOLD_EMP
  FOREIGN KEY (EMP_ID)
  REFERENCES HRMS.EMPLOYEES (ID)
  ENABLE VALIDATE
, CONSTRAINT FK_HR_INC_HOLD_INCREMENT
  FOREIGN KEY (INCREMENT_ID)
  REFERENCES HRMS.HR_EMPLOYEE_INCREMENT (INCREMENT_ID)
  ENABLE VALIDATE
, CONSTRAINT FK_HR_INC_HOLD_ACTION
  FOREIGN KEY (ACTION_ID)
  REFERENCES HRMS.HR_EMPLOYEE_ACTION (ACTION_ID)
  ENABLE VALIDATE
, 
  PRIMARY KEY
  (HOLD_ID)
  USING INDEX
    TABLESPACE HRMS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);


DROP SEQUENCE HRMS.ISEQ$$_226104;

-- Sequence ISEQ$$_226104 is created automatically by Oracle for use with an Identity column


--  There is no statement for index HRMS.SYS_C0024995.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX HRMS.UQ_HR_INC_HOLD_ACTIVE
    ON HRMS.HR_INCREMENT_HOLD
       (CASE WHEN HOLD_STATUS = 'ACTIVE' THEN INCREMENT_ID END);

CREATE INDEX HRMS.IDX_HR_INC_HOLD_EMP_STATUS
    ON HRMS.HR_INCREMENT_HOLD (EMP_ID, HOLD_STATUS);
