DROP TABLE HRMS.LEAVE_CONSUMPTION CASCADE CONSTRAINTS;

CREATE TABLE HRMS.LEAVE_CONSUMPTION
(
  CONSUMPTION_ID    NUMBER,
  EMPID             NUMBER,
  LEAVE_TYPE_ID     NUMBER,
  CONSUMED_DAYS     NUMBER                      NOT NULL,
  CONSUMPTION_DATE  DATE                        DEFAULT SYSDATE,
  START_DATE        DATE,
  END_DATE          DATE,
  ENT_DATE          DATE                        DEFAULT SYSDATE,
  ENT_BY            NUMBER,
  UPD_DATE          DATE,
  UPD_BY            NUMBER,
  COM_ID            NUMBER,
  CONSUM_YEAR       NUMBER
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


ALTER TABLE HRMS.LEAVE_CONSUMPTION ADD (
  PRIMARY KEY
  (CONSUMPTION_ID)
  USING INDEX
    TABLESPACE HRMS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);


--  There is no statement for index HRMS.SYS_C0020275.
--  The object is created when the parent object is created.

ALTER TABLE HRMS.LEAVE_CONSUMPTION ADD (
  FOREIGN KEY (EMPID) 
  REFERENCES HRMS.EMPLOYEES (ID)
  ENABLE VALIDATE
,  FOREIGN KEY (LEAVE_TYPE_ID) 
  REFERENCES HRMS.LEAVE_TYPES (LT_ID)
  ENABLE VALIDATE);
