DROP TABLE HRMS.LEAVE_TYPES CASCADE CONSTRAINTS;

CREATE TABLE HRMS.LEAVE_TYPES
(
  LT_ID            NUMBER,
  SHORT_CODE       VARCHAR2(5 BYTE),
  LEAVE_TYPE_NAME  VARCHAR2(50 BYTE)            NOT NULL,
  DESCRIPTION      VARCHAR2(100 BYTE),
  ANNUAL_QUOTA     NUMBER,
  IS_PAID          CHAR(1 BYTE),
  ACTIVE_FLAG      CHAR(1 BYTE)                 DEFAULT 'Y',
  ENT_BY           VARCHAR2(50 BYTE),
  ENT_DATE         DATE                         DEFAULT SYSDATE,
  UPD_BY           VARCHAR2(50 BYTE),
  UPD_DATE         DATE,
  COM_ID           NUMBER
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.LEAVE_TYPES_PK ON HRMS.LEAVE_TYPES
(LT_ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.LEAVE_TYPES ADD (
  CHECK (is_paid IN ('Y', 'N'))
  ENABLE VALIDATE
,  CHECK (active_flag IN ('Y', 'N'))
  ENABLE VALIDATE
,  CONSTRAINT LEAVE_TYPES_PK
  PRIMARY KEY
  (LT_ID)
  USING INDEX HRMS.LEAVE_TYPES_PK
  ENABLE VALIDATE);
