DROP TABLE HRMS.LOCATIONS CASCADE CONSTRAINTS;

CREATE TABLE HRMS.LOCATIONS
(
  ID        NUMBER,
  NAME      VARCHAR2(50 BYTE),
  ADDRESS   VARCHAR2(100 BYTE),
  PHONE     VARCHAR2(30 BYTE),
  EMAIL     VARCHAR2(30 BYTE),
  COM_ID    NUMBER,
  ENT_BY    NUMBER,
  ENT_DATE  DATE,
  UPD_BY    NUMBER,
  UPD_DATE  DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.LOCATIONS_PK ON HRMS.LOCATIONS
(ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.LOCATIONS ADD (
  CONSTRAINT LOCATIONS_PK
  PRIMARY KEY
  (ID)
  USING INDEX HRMS.LOCATIONS_PK
  ENABLE VALIDATE);


CREATE OR REPLACE TRIGGER HRMS.TRG_LOCATIONS_PK
    BEFORE INSERT OR UPDATE
    ON HRMS.LOCATIONS
    FOR EACH ROW
BEGIN
    IF :new.id IS NULL
    THEN
        SELECT NVL (MAX (id), 0) + 1 INTO :new.id FROM LOCATIONS;
    END IF;
END TRG_LOCATIONS_PK;
/
