DROP TABLE HRMS.MONTHLY_SALARY_ADJUSTMENT CASCADE CONSTRAINTS;

CREATE TABLE HRMS.MONTHLY_SALARY_ADJUSTMENT
(
  MSA_ID        NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  EMPLOYEE_ID   NUMBER                          NOT NULL,
  SALARY_MONTH  NUMBER(6)                       NOT NULL,
  HEADCODE      VARCHAR2(10 BYTE),
  HEAD_NAME     VARCHAR2(200 BYTE),
  HEAD_TYPE     VARCHAR2(20 BYTE),
  AMOUNT        NUMBER(12,2),
  REMARKS       VARCHAR2(500 BYTE),
  CREATED_BY    NUMBER,
  CREATED_DATE  DATE                            DEFAULT SYSDATE,
  UPDATED_BY    NUMBER,
  UPDATED_DATE  DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


ALTER TABLE HRMS.MONTHLY_SALARY_ADJUSTMENT ADD (
  PRIMARY KEY
  (MSA_ID)
  USING INDEX
    TABLESPACE HRMS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);


DROP SEQUENCE HRMS.ISEQ$$_220343;

-- Sequence ISEQ$$_220343 is created automatically by Oracle for use with an Identity column


--  There is no statement for index HRMS.SYS_C0024444.
--  The object is created when the parent object is created.
