DROP TABLE HRMS.MONTHLY_SALARY_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE HRMS.MONTHLY_SALARY_DETAILS
(
  MSD_ID        NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 732721 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  MS_ID         NUMBER                          NOT NULL,
  EMPLOYEE_ID   NUMBER                          NOT NULL,
  SALARY_MONTH  NUMBER(6)                       NOT NULL,
  SLNO          NUMBER,
  HEADCODE      VARCHAR2(10 BYTE),
  HEAD_NAME     VARCHAR2(200 BYTE),
  HEAD_TYPE     VARCHAR2(20 BYTE),
  AMOUNT        NUMBER(12,2),
  SOURCE        VARCHAR2(20 BYTE)               DEFAULT 'STRUCTURE',
  REMARKS       VARCHAR2(500 BYTE),
  CREATED_BY    NUMBER,
  CREATED_DATE  DATE                            DEFAULT SYSDATE,
  UPDATED_BY    NUMBER,
  UPDATED_DATE  DATE
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


ALTER TABLE HRMS.MONTHLY_SALARY_DETAILS ADD (
  PRIMARY KEY
  (MSD_ID)
  USING INDEX
    TABLESPACE HRMS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);


DROP SEQUENCE HRMS.ISEQ$$_220340;

-- Sequence ISEQ$$_220340 is created automatically by Oracle for use with an Identity column


CREATE INDEX HRMS.IDX_SALARY_DETAILS_COMPOUND ON HRMS.MONTHLY_SALARY_DETAILS
(MS_ID, EMPLOYEE_ID, SALARY_MONTH, HEADCODE, AMOUNT)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
COMPRESS 3;

CREATE INDEX HRMS.IDX_SALARY_DETAILS_EMPLOYEE ON HRMS.MONTHLY_SALARY_DETAILS
(EMPLOYEE_ID, SALARY_MONTH, HEADCODE)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
COMPRESS 2;

--  There is no statement for index HRMS.SYS_C0024439.
--  The object is created when the parent object is created.

ALTER TABLE HRMS.MONTHLY_SALARY_DETAILS ADD (
  FOREIGN KEY (MS_ID) 
  REFERENCES HRMS.MONTHLY_SALARY (MS_ID)
  ENABLE VALIDATE);
