DROP TABLE HRMS.PAY_SCALE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE HRMS.PAY_SCALE_DETAIL
(
  DETAIL_ID         NUMBER,
  SCALE_ID          NUMBER                      NOT NULL,
  STEP_NO           NUMBER(3)                   NOT NULL,
  BASIC_AMOUNT      NUMBER(10,2)                NOT NULL,
  INCREMENT_AMOUNT  NUMBER(10,2),
  IS_EB_STEP        VARCHAR2(1 BYTE)            DEFAULT 'N'                   NOT NULL,
  PHASE             VARCHAR2(10 BYTE)           NOT NULL
)
TABLESPACE HRMS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX HRMS.PAY_SCALE_DETAIL_PK ON HRMS.PAY_SCALE_DETAIL
(DETAIL_ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX HRMS.UK_SCALE_STEP ON HRMS.PAY_SCALE_DETAIL
(SCALE_ID, STEP_NO)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE HRMS.PAY_SCALE_DETAIL ADD (
  CONSTRAINT CHK_DETAIL_EB
  CHECK (is_eb_step IN ('Y','N'))
  ENABLE VALIDATE
,  CONSTRAINT CHK_DETAIL_STEP_RANGE
  CHECK (step_no BETWEEN 0 AND 25)
  ENABLE VALIDATE
,  CONSTRAINT CHK_DETAIL_STEP_CONTENT
  CHECK (
      (step_no = 0 AND phase = 'INITIAL' AND increment_amount IS NULL)
      OR
      (step_no BETWEEN 1 AND 25
       AND phase IN ('PRE_EB','POST_EB')
       AND increment_amount > 0)
  )
  ENABLE VALIDATE
,  CONSTRAINT CHK_DETAIL_PHASE
  CHECK (phase IN ('INITIAL','PRE_EB','POST_EB'))
  ENABLE VALIDATE
,  CONSTRAINT PAY_SCALE_DETAIL_PK
  PRIMARY KEY
  (DETAIL_ID)
  USING INDEX HRMS.PAY_SCALE_DETAIL_PK
  ENABLE VALIDATE
,  CONSTRAINT UK_SCALE_STEP
  UNIQUE (SCALE_ID, STEP_NO)
  USING INDEX HRMS.UK_SCALE_STEP
  ENABLE VALIDATE);


CREATE INDEX HRMS.IDX_DETAIL_BASIC ON HRMS.PAY_SCALE_DETAIL
(BASIC_AMOUNT)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX HRMS.IDX_DETAIL_SCALE ON HRMS.PAY_SCALE_DETAIL
(SCALE_ID)
LOGGING
TABLESPACE HRMS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER HRMS.t_pay_scale_detail_pk
    BEFORE INSERT OR UPDATE
    ON HRMS.PAY_SCALE_DETAIL
    FOR EACH ROW
BEGIN
    IF :new.DETAIL_ID IS NULL
    THEN
        SELECT NVL (MAX (DETAIL_ID), 0) + 1
          INTO :new.DETAIL_ID
          FROM pay_scale_detail;
    END IF;
END t_pay_scale_detail_pk;
/


ALTER TABLE HRMS.PAY_SCALE_DETAIL ADD (
  CONSTRAINT FK_DETAIL_SCALE 
  FOREIGN KEY (SCALE_ID) 
  REFERENCES HRMS.PAY_SCALE_MASTER (SCALE_ID)
  ENABLE VALIDATE);
